### ISSUE TITLE
Plugin throws and error after upgrading tns to 6.1.2

### ISSUE THREAD

**Issue by Omar-Al-Ashi** [bthurlow/nativescript-imagecropper#64] opened 2019-11-01 11:04 UTC
### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

*The plugin works perfectly on iOS (both emulator and physical device). On the other hand, it throws and error on Android
*Tns Android version: 6.1.2

### Please, provide the following version numbers that your issue occurs with:
*CLI: 6.1.2

### Please, tell us how to recreate the issue in as much detail as possible.

I set an image picker to pick a picture from the gallery, after that is done, I send the source of the image to the imagecropper plugin, whenever the imagecropper method is called, an error gets thrown which is as follows:

```
What went wrong:
Execution failed for task ':verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/user_name/project-name/platforms/tempPlugin/nativescript_imagecropper/src/main/AndroidManifest.xml:3:3-5:17: AAPT: error: attribute android:requestLegacyExternalStorage not found.
```

> 

>

**Comment by shiv19** [comment] 2019-11-01 20:16
Duplicate of #63 
@Omar-Al-Ashi can you please try the resolution on #63 and let me know if it works for you?

**Closed by shiv19** 2019-11-01 20:16 UTC

**Comment by Omar-Al-Ashi** [comment] 2019-11-05 15:10
I have applied the solution in the issue #63, now it builds successfully but whenever I call the plugin I receive this error

` 'No v4 support'
JS: [Error: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=28513, uid=10375 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
JS:     android.os.Parcel.createException(Parcel.java:1950)
JS:     android.os.Parcel.readException(Parcel.java:1918)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
JS:     android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
JS:     android.content.ContentProviderProxy.query(ContentProviderNative.java:432)
JS:     android.content.ContentResolver.query(ContentResolver.java:847)
JS:     android.content.ContentResolver.query(ContentResolver.java:762)
JS:     android.content.ContentResolver.query(ContentResolver.java:720)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
JS:     com.tns.Runtime.callJSMethod(Runtime...
`

Any suggestion would be much appreciated

**Comment by shiv19** [comment] 2019-11-05 17:42
Looks like you haven't requested for READ_EXTERNAL_STORAGE permission. 

android.permission.READ_EXTERNAL_STORAGE

**Comment by Omar-Al-Ashi** [comment] 2019-11-05 18:14
I did actually in my AndroidManifest.xml. I tried adding it to the plugin's Manifest as well but didn't work either :/ 
Btw thank you for your prompt responses.

**Comment by shiv19** [comment] 2019-11-05 18:20
It's not enough to add it, you should request permission from the user
Use something like nativescript-permissions
And request for WRITE_EXTERNAL_STORAGE permission

**Comment by Omar-Al-Ashi** [comment] 2019-11-06 07:43
Thank you, it worked 👍🏽I thought it was enough to get the permission in AndroidManifest.
Much appreciated
